version: "3.8"

services:
  mongo:
    container_name: fitness-app-mongo
    restart: always
    build:
      context: ./mongo
    env_file:
      - ./env/mongo.env
    networks:
      - mongo-server
  
  mysql:
    container_name: fitness-app-mysql
    restart: always
    build:
      context: ./mysql
    env_file:
      - ./env/mysql.env
    networks:
      - mysql-server
  
  server:
    container_name: fitness-app-back
    build:
      context: ./server
    ports:
      - 8080:8080
    env_file:
      - ./env/server.env
    depends_on:
      - mongo
      - mysql
    networks:
      - mysql-server
      - mongo-server
      # - react-server
  
  front:
    container_name: fitness-app-front
    build:
      context: ./front
    ports:
      - 3000:3000
    depends_on:
      - server
    # networks:
    #   - react-server

networks:
  mysql-server:
  mongo-server:
  # react-server: